/** Architectures known to work with vLLM. */
export const VLLM_SUPPORTED_ARCHITECTURES = [
  'llama',
  'mistral',
  'mixtral',
  'qwen',
  'qwen2',
  'qwen3',
  'falcon',
  'mpt',
  'starcoder',
  'starcoder2',
  'codellama',
  'phi',
  'phi3',
  'gemma',
  'gemma2',
  'deepseek',
  'kimi',
  'internlm',
  'internlm2',
  'yi',
  'baichuan',
  'chatglm',
  'glm4',
  'glm',
  'bloom',
  'opt',
  'gpt2',
  'gpt-j',
  'gpt-neox',
  'pythia',
  'stablelm',
  'dbrx',
  'command-r',
  'olmo',
  'arctic',
  'jamba',
  'exaone',
  'minimax',
  'lfm2',
  'gpt_oss',
  'nemotron',
  'nemotron_h',
] as const;

/** HuggingFace pipeline tags that indicate text-generation capability. */
export const TEXT_GENERATION_TASKS = [
  'text-generation',
  'text2text-generation',
  'conversational',
] as const;

/** Model-ID format accepted by the HuggingFace API. */
export const MODEL_ID_PATTERN = /^[\w-]+\/[\w.-]+$|^[\w.-]+$/;
